import os
import glob
import pandas as pd

# CONFIGURATION
base_folder = "database"
sidebar_file = "sidebar_config.yml" # We write to the ROOT folder now
material_links = []

print("--- Starting Database Build ---")

# 1. Loop through folders to build pages (Standard)
for item in os.listdir(base_folder):
    item_path = os.path.join(base_folder, item)
    
    if os.path.isdir(item_path) and not item.startswith('.'):
        material_name = item
        print(f"Processing: {material_name}")
        
        # SAVE THE LINK: Note we include 'database/' in the path now
        material_links.append(f"database/{material_name}/index.qmd")

        # --- [Content Generation] ---
        summary_path = os.path.join(item_path, "summary.txt")
        summary_text = "_No summary provided._"
        if os.path.exists(summary_path):
            with open(summary_path, 'r') as f: summary_text = f.read()

        csv_path = os.path.join(item_path, "properties.csv")
        table_markdown = ""
        if os.path.exists(csv_path):
            try:
                df = pd.read_csv(csv_path)
                table_markdown = df.to_markdown(index=False) 
            except: pass

        image_files = glob.glob(os.path.join(item_path, "*.png")) + \
                      glob.glob(os.path.join(item_path, "*.jpg"))
        image_markdown = ""
        if image_files:
            img_name = os.path.basename(image_files[0])
            image_markdown = f"![Structure]({img_name})"

        page_content = f"""---
title: "{material_name}"
format:
  html:
    toc: true
---

## Overview
{summary_text}

## Key Properties
{table_markdown}

## Characterization
{image_markdown}
"""
        with open(os.path.join(item_path, "index.qmd"), "w") as f:
            f.write(page_content)

# 2. GENERATE THE EXTERNAL CONFIG FILE
# This writes the sidebar settings into a separate file that _quarto.yml imports
print(f"Updating {sidebar_file}...")

with open(sidebar_file, "w") as f:
    f.write("# AUTO-GENERATED BY PYTHON. DO NOT EDIT.\n")
    f.write("website:\n")
    f.write("  sidebar:\n")
    f.write("    - title: 'Material Database'\n")
    f.write("      style: docked\n")
    f.write("      background: '#f8f9fa'\n")
    f.write("      contents:\n")
    f.write("        - href: database/index.qmd\n")
    f.write("          text: 'Overview'\n")
    f.write("        - section: 'Available Materials'\n")
    f.write("          contents:\n")
    
    # Write the explicitly automated list
    for link in sorted(material_links):
        f.write(f"            - href: {link}\n")
        # Extract name: "database/Bi2Se3/index.qmd" -> "Bi2Se3"
        display_name = link.split('/')[1] 
        f.write(f"              text: '{display_name}'\n")

print("--- Build Complete! ---")